export const DRAWER_STATE = "DRAWER_STATE"

export const GET_VODKA_DRINKS = "GET_VODKA_DRINKS"
export const VODKA_DRINKS_RECEIVED = "VODKA_DRINKS_RECEIVED"
export const VODKA_DRINKS_ERROR = "VODKA_DRINKS_ERROR"

export const GET_DRINK_BY_ID = "GET_DRINK_BY_ID"
export const GET_DRINK_BY_ID_RECEIVED = "GET_DRINK_BY_ID_RECEIVED"
export const GET_DRINK_BY_ID_ERROR = "GET_DRINK_BY_ID_ERROR"

export const GET_ALL_DRINKS_AL = "GET_ALL_DRINKS_AL"
export const GET_ALL_DRINKS_AL_RECEIVED = "GET_ALL_DRINKS_AL_RECEIVED"
export const GET_ALL_DRINKS_AL_ERROR = "GET_ALL_DRINKS_AL_ERROR"
